image: ekidd/rust-musl-builder:nightly-2020-04-10

stages:
  - test

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

test:
  stage: test
  script:
    - cargo test

fmt:
  stage: test
  script:
    - cargo fmt --all -- --check

clippy:
  stage: test
  script:
    - cargo clippy -- -D warnings

cache:
  paths:
    - target/
    - cargo/