stages:
  - test

test:
  stage: test
  image: ekidd/rust-musl-builder:nightly-2020-04-10
  script:
    - cargo test

fmt:
  stage: test
  image: ekidd/rust-musl-builder:nightly-2020-04-10
  script:
    - cargo fmt --all -- --check

clippy:
  stage: test
  image: ekidd/rust-musl-builder:nightly-2020-04-10
  script:
    - cargo clippy -- -D warnings

cache:
  paths:
    - target/