version: "3"
services:
  nginx:
    image: nginx:1-alpine
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
  mediaproxy:
    build: .
    expose:
      - "80"
