version: "3.4"
services:
  nginx:
    image: nginx:1-alpine
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
  mediaproxy-server:
    build: mediaproxy-server
  mediaproxy-router:
    build: mediaproxy-router
    command: --forward nginx:80
    ports:
      - "80:80"
