{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "ingress.fullname" . }}
  labels:
    {{- include "ingress.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .name }}
    http:
      paths:
      - path: "/"
        backend:
          serviceName: {{ template "router.fullname" $ }}
          servicePort: http
  tls:
  {{- if .Values.ingress.tls }}
  - hosts:
    - {{- .Values.ingress.host }}
  {{- end }}
{{- end }}