name: Lint and Test Charts

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v1.0.0
        with:
          exec: helm lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: engineerd/setup-kind@v0.4.0

      - name: Read kubeconfig
        id: kubeconfig
        uses: juliangruber/read-file-action@v1
        with:
          path: ~/.kube/config

      - uses: WyriHaximus/github-action-helm3@v2.0
        with:
          exec: helm install mediaproxy . --wait --set router.service.type=NodePort
          kubeconfig: ${{ steps.kubeconfig.outputs.content }}
      
      - name: Test
        run: kubectl get all