name: Lint and Test Charts

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v1.0.0
        with:
          exec: helm lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: engineerd/setup-kind@v0.4.0
      - uses: azure/setup-helm@v1
      - run: brew install yq

      # - uses: pCYSl5EDgo/cat@master
      #   id: kubeconfig
      #   with:
      #     path: ~/.kube/config

      - run: |
          helm install mediaproxy . --wait \
            --set router.service.type=NodePort \
            --set server.resources.requests.cpu=512m \
            --set server.resources.requests.memory=512Mi \
            --set server.resources.limits.cpu=512m \
            --set server.resources.limits.memory=512Mi \

      - name: Get router port
        run: |
          echo ::set-env name=ROUTER_PORT::$(kubectl get svc mediaproxy-mediaproxy-router -o yaml | yq r -)

      - run: cat ${{ env.ROUTER_PORT }}