name: Update image tags

on:
  repository_dispatch:
    types: [image_pushed]

jobs:
  update:
    name: Update chart
    runs-on: ubuntu-latest
    steps:
      - id: server
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: ThePicoNerd
          repo: mediaproxy-server

      - id: router
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: ThePicoNerd
          repo: mediaproxy-router

      - uses: actions/checkout@v2

      - name: Install yq
        run: brew install yq

      - run: yq w -i values.yaml server.image.tag ${{ steps.server.outputs.release }}
      - run: yq w -i values.yaml router.image.tag ${{ steps.router.outputs.release }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          title: Update chart image tags
          body: |
            Versions:
            - [mediaproxy-server](https://github.com/ThePicoNerd/mediaproxy-server) **${{ steps.server.outputs.release }}**
            - [mediaproxy-router](https://github.com/ThePicoNerd/mediaproxy-server) **${{ steps.router.outputs.release }}**
          labels: dependencies